### ISSUE TITLE
In runner.js ES6 function startsWith is used

### ISSUE THREAD

**Issue by pauliusg** [scharf/mocha-for-jetbrains#1]
In runner.js ES6 function startsWith is used.
So, in WebStorm I get error: 

C:...\node_modules\mocha-for-jetbrains\impl\runner.js:5
        if (arr[i].startsWith('-')) {
                   ^
TypeError: undefined is not a function
    at indexOfDash (C:...\node_modules\mocha-for-jetbrains\impl\runner.js:5:20)
    at Object.rewite [as rewrite](C:...node_modulesmocha-for-jetbrainsimplrunner.js:39:30)
    at Object.<anonymous> (C:...\node_modules\mocha-for-jetbrains\bin_mocha:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout](module.js:501:10)
    at Timer.listOnTimeout (timers.js:110:15)

Process finished with exit code 1

**Comment by scharf** [comment]
fixed in version `1.0.1`
